# Generated by Django 6.0 on 2025-12-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('result', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('search_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
